# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  base = "docs/"
  command = "make"

[[redirects]]
  from = "http://docs.dev.to"
  to = "https://docs.dev.to"
[[redirects]]
  from = "http://docs.dev.to/ruby-doc"
  to = "https://docs.dev.to/ruby-doc/index.html"
[[redirects]]
  from = "http://docs.dev.to/ruby-doc/"
  to = "https://docs.dev.to/ruby-doc/index.html"
[[redirects]]
  from = "http://docs.dev.to/*"
  to = "https://docs.dev.to/:splat"
  status = 301
[[redirects]]
  from = "docs.dev.to"
  to = "https://docs.dev.to"
[[redirects]]
  from = "docs.dev.to/*"
  to = "https://docs.dev.to/:splat"
  status = 301
[[redirects]]
  from = "http://devto.netlify.com"
  to = "https://docs.dev.to"
[[redirects]]
  from = "http://devto.netlify.com/*"
  to = "https://docs.dev.to/:splat"
  status = 301
[[redirects]]
  from = "https://devto.netlify.com"
  to = "https://docs.dev.to"
[[redirects]]
  from = "https://devto.netlify.com/*"
  to = "https://docs.dev.to/:splat"
  status = 301
