version: "3"

x-uffizzi:
  ingress:
    service: rails
    port: 3000

services:
  rails:
    image: "${APP_IMAGE}"
    container_name: forem_rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://forem:forem@localhost:5432/PracticalDeveloper_development
      REDIS_SESSIONS_URL: redis://localhost:6379
      REDIS_SIDEKIQ_URL: redis://localhost:6379
      REDIS_URL: redis://localhost:6379
      RACK_TIMEOUT_WAIT_TIMEOUT: 10000
      RACK_TIMEOUT_SERVICE_TIMEOUT: 10000
      STATEMENT_TIMEOUT: 10000
      APP_DOMAIN: localhost:3000
      APP_PROTOCOL: https://
    entrypoint: ["dockerize", "-wait", "tcp://localhost:5432", "-wait", "tcp://localhost:6379", "-wait", "file:///opt/apps/forem/vendor/bundle/.bundle_finished", "-timeout", "5400s"]
    command: [ "bash", "-c", "./scripts/entrypoint.sh bootstrap && bundle exec rails server -b 0.0.0.0 -p 3000"]
    deploy:
      resources:
        limits:
          memory: 4000M     

  seed:
    image: "${APP_IMAGE}"
    container_name: forem_seed
    depends_on:
      - rails
      - redis
      - db
    environment:
      RAILS_ENV: development
      REDIS_SESSIONS_URL: redis://localhost:6379
      REDIS_SIDEKIQ_URL: redis://localhost:6379
      REDIS_URL: redis://localhost:6379
      DATABASE_URL: postgresql://forem:forem@localhost:5432/PracticalDeveloper_development
    entrypoint: ["dockerize", "-wait", "tcp://localhost:5432", "-wait", "tcp://localhost:6379", "-wait", "http://localhost:3000", "-timeout", "5400s"]
    command: ["./uffizzi/db_seed.sh"]
    deploy:
      resources:
        limits:
          memory: 500M

  sidekiq:
    image: "${APP_IMAGE}"
    container_name: forem_sidekiq
    depends_on:
      - rails
      - redis
      - db
    environment:
      RAILS_ENV: development
      REDIS_SESSIONS_URL: redis://localhost:6379
      REDIS_SIDEKIQ_URL: redis://localhost:6379
      REDIS_URL: redis://localhost:6379
      DATABASE_URL: postgresql://forem:forem@localhost:5432/PracticalDeveloper_development
    entrypoint: ["dockerize", "-wait", "tcp://localhost:5432", "-wait", "tcp://localhost:6379", "-wait", "http://localhost:3000", "-timeout", "5400s"]
    command: ["bundle", "exec", "sidekiq","-c","2"]
    deploy:
      resources:
        limits:
          memory: 500M

  db:
    image: postgres:11-alpine
    container_name: forem_postgresql
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: forem
      POSTGRES_DB: PracticalDeveloper_development
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0.9-alpine
    container_name: forem_redis
    ports:
      - "6379:6379"
