# See: https://github.com/github/super-linter

name: Lint Code Base

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          # Only validate new and modified files
          VALIDATE_ALL_CODEBASE: true
          # By default the action looks for rules files in .github/linters/ so
          # we change this to the repository root.
          LINTER_RULES_PATH: /
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NOTE: If no VALIDATE_* variables are set all default to true. As
          # soon as one is set, all others default to false.
          # Validate Ruby with RuboCop
          VALIDATE_RUBY: true
          RUBY_CONFIG_FILE: .rubocop.yml
          # Validatate JS with ESLint
          VALIDATE_JAVASCRIPT_ES: true
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          JAVASCRIPT_DEFAULT_STYLE: prettier
          # Validate OpenAPI with Spectral
          VALIDATE_OPENAPI: true



